# version: "3.3" # version of docker compose you can choose the latest
version: '3'
services:
  app:
#    image: registry.gitlab.com/nanuchi/mynodeapp-cicd-project:1.2 # copied from one of the versions of the image in gitlab's container registry
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    ports:
      - 3000:3000 # the same as: docker run -d -p 3000:3000 $IMAGE_NAME:$IMAGE_TAG that is used in ci config.

  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
